# -*- coding: utf-8 -*-
"""Configuration file for the Sphinx documentation builder."""

import os
import sys

# Prepare Qt for docs.
from Qt import QtCore
if not hasattr(QtCore.Signal, "signatures"):
    QtCore.Signal.signatures = ()

# Path setup.
root_path = os.path.abspath(os.path.join("..", ".."))
sys.path.insert(0, root_path)

# Project information.
project = "Objetto Qt"
copyright = "2020, Bruno Nicko"
author = "Bruno Nicko"

# Sphinx extensions.
extensions = [
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.autodoc",
    "sphinx_rtd_theme",
    "sphinx_qt_documentation",
]

# Sphinx Qt documentation configuration.
qt_documentation = "Qt5"

# Intersphinx configuration.
intersphinx_mapping = {
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "python": ("https://docs.python.org/3.8", None),
    "six": ("https://six.readthedocs.io/", None),
    "objetto": ("https://objetto.readthedocs.io/en/stable/", None),
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5/", None),
}

# Autodoc configuration.
autoclass_content = "class"
autodoc_typehints = "none"
autodoc_member_order = "bysource"

# Templates' paths.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = None

# List of patterns to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "monokai"

# HTML options.
html_theme = "sphinx_rtd_theme"
html_theme_options = {}
html_static_path = ["_static"]

# LaTeX options.
latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
    "preamble": "",
    "figure_align": "htbp",
}
latex_documents = [
    (master_doc, "ObjettoQt.tex", "Objetto Qt Documentation", "Bruno Nicko", "manual"),
]

# Manual Page options.
man_pages = [
    (master_doc, "objettoqt", "Objetto Qt Documentation", [author], 1),
]

# Texinfo options.
texinfo_documents = [
    (
        master_doc,
        "ObjettoQt",
        "Objetto Qt Documentation",
        author,
        "ObjettoQt",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# ePub options.
epub_title = project
epub_exclude_files = ["search.html"]
